"""Add journal entry relationship to Task

Revision ID: f58f0b8b264a
Revises: 7f6909310d26
Create Date: 2025-07-31 13:58:14.462216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58f0b8b264a'
down_revision = '7f6909310d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_entry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_journal_entry', 'journal_entry', ['journal_entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('journal_entry_id')

    # ### end Alembic commands ###
